import Header from '@/components/Header'
import Head from 'next/head'
import Inscribe from './inscribe'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ordinal.art - Inscribe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='fix'>
        <div className="gradient-position">
          <img
            src="/images/gradient-circle.svg"
            style={{ left: "-4%", top: "-4%" }}
            width="500"
            alt="Background Circle"
          />
          <img
            src="/images/gradient-circle.svg"
            style={{ right: "-4%", bottom: "-4%" }}
            width="500"
            alt="Background Circle"
          />
        </div>
        <Inscribe />
      </main>
    </>
  )
}
